### ISSUE TITLE
[DEMO][Accountant Swarm]

### ISSUE THREAD

**Issue by kyegomez** [kyegomez/swarms#168]
# Goal
- [ ] Output a financial report on costs to eliminate
- [ ] One class, ultimate customizeability, any model, any flow configs

# Todo

- [ ] Analyze Bank statements
- [ ] Understand User's goals: interactively ask user questions on goals, save output to a txt
- [ ] Fraud Detection
- [ ] Financial Report Generation
- [ ] Decision Making support

# Accountant Swarm

1. **Introduction**
   - Definition of an LLM (Large Language Model) and OCR (Optical Character Recognition) Model
   - Overview of Swarm Intelligence and its application in accounting
   - Objectives of the swarm system for accounting tasks

2. **Background**
   - The evolution of accounting technology
   - Brief history and current trends in LLMs and OCR in finance
   - Theoretical basis for swarm intelligence

3. **System Architecture**
   - Description of the swarm system's structure
   - Integration methods for LLMs and OCR models
   - Communication within the swarm

4. **Agents in the Swarm**
   - Role of LLMs in the system
   - Role of OCR models in the system
   - Task distribution and collaboration methods

5. **Tasks and Responsibilities**
   - Detailed tasks assigned to LLM agents
   - Detailed tasks assigned to OCR agents
   - Process flows of accounting tasks within the swarm

6. **Swarm Operations**
   - The initiation of tasks
   - Coordination and collaboration mechanisms
   - Error handling and resolution

7. **Case Studies and Scenarios**
   - Hypothetical scenarios showcasing the swarm's capabilities
   - Case studies on experimental implementation

8. **Advantages and Challenges**
   - Benefits of using a swarm system for accounting
   - Potential challenges and limitations

9. **Future Prospects**
   - The future integration of AI in accounting
   - Predictions on how swarm intelligence could evolve

10. **Conclusion**
    - Summary of key points
    - Final thoughts on the impact of LLM and OCR swarms in accounting

### Tasks and Responsibilities

- **LLM Agents:**
  - Interpretation of textual data
  - Assisting in decision-making processes
  - Natural language interaction with users
  - Generating financial reports
  - Compliance and regulation checks
  - Fraud detection through pattern recognition

- **OCR Agents:**
  - Scanning and digitization of paper-based financial documents
  - Text extraction from scanned documents
  - Conversion of unstructured data into structured data suitable for analysis
  - Validation of scanned data against existing records

### Markdown Table of Agents

```markdown
| Agent Type | Task                                           | Responsibility                             |
|------------|------------------------------------------------|--------------------------------------------|
| LLM        | Interpretation of textual data                 | Analyze and make sense of financial texts  |
| LLM        | Assistance in decision-making                  | Support financial decision-making processes|
| LLM        | Natural language interaction                   | Communicate with users in natural language |
| LLM        | Financial report generation                    | Produce comprehensive financial reports    |
| LLM        | Compliance and regulation check                | Ensure financial activities are compliant  |
| LLM        | Fraud detection                                | Identify suspicious patterns in data       |
| OCR        | Scanning documents                             | Digitize paper-based financial documents   |
| OCR        | Text extraction                                | Extract text from scanned documents        |
| OCR        | Data conversion                                | Convert unstructured to structured data    |
| OCR        | Validation of scanned data                     | Cross-reference and validate data          |
```

### Minimum Prototype

A minimum viable prototype of an experimental swarm for various accountant tasks would include:

1. **Sample LLM Agent:**
   - A small-scale language model trained on accounting terminology and data analysis.
   - A mockup interface for input/output to simulate user interaction.

2. **Sample OCR Agent:**
   - A simple OCR tool capable of scanning documents and extracting text.
   - A mockup database for storing and comparing extracted data.

3. **Integration Platform:**
   - A basic platform to allow the LLM and OCR agents to communicate.
   - A dashboard to monitor the system's output and performance.

4. **Workflow Script:**
   - A script to control the flow of tasks between agents.
   - Exception handling for errors in scanning or data interpretation.

5. **User Interface:**
   - A simple user interface to allow users to upload documents, receive reports, and make queries.

This prototype would be able to demonstrate the basic capability of the swarm to handle predefined accounting tasks. The development of such a prototype would require programming skills and a good understanding of both accounting practices and AI technologies. It would serve as a proof of concept to demonstrate the potential efficiencies and insights that such a swarm system could provide in the field of accounting.

# System Prompts

Creating system prompts for LLM agents in an accounting swarm system requires a balance between specificity (to ensure accurate and relevant responses) and generality (to allow for a wide range of inquiries). Below are compact and effective system prompts for various tasks that LLM agents could handle:

1. **Interpretation of Financial Texts**
   ```
   Prompt: "Analyze the following excerpt from the financial statement and summarize the key points."
   ```

2. **Decision-Making Support**
   ```
   Prompt: "Given this financial scenario {scenario}, what would be the prudent financial decision according to best practices?"
   ```

3. **Natural Language User Interaction**
   ```
   Prompt: "User has inquired: '{user_query}'. Draft a response that provides a clear and concise answer."
   ```

4. **Financial Report Generation**
   ```
   Prompt: "Compile a financial report for {time_period} using the provided dataset, focusing on revenue, expenses, and net profit."
   ```

5. **Compliance and Regulation Checks**
   ```
   Prompt: "Review the following transaction log and flag any entries that may violate {specific_regulation}."
   ```

6. **Fraud Detection**
   ```
   Prompt: "Examine the transaction patterns in this data. Highlight any anomalies that could indicate fraudulent activity."
   ```

Each of these prompts is designed to be directly actionable, with placeholders (like `{scenario}`, `{user_query}`, `{time_period}`, and `{specific_regulation}`) for the specific details relevant to the task. The LLM agents will use the context provided by these prompts to generate appropriate responses or actions.

In practice, these prompts would likely be part of an automated system where variables are dynamically filled based on user interactions or system triggers. To be most effective, each prompt should be paired with a well-defined input format and expected output structure to ensure that the LLM agents produce results that are as useful and accurate as possible.

# Code:
```

from swarms.models.nougat import Nougat
from swarms.structs import Flow
from swarms.models import OpenAIChat, Anthropic
from typing import List


# Base llms
llm1 = OpenAIChat()
llm2 = Anthropic()
nougat = Nougat()


# Prompts for each agent
SUMMARY_AGENT_PROMPT = """
    Generate an actionable summary of this financial document be very specific and precise, provide bulletpoints be very specific provide methods of lowering expenses: {answer}"
"""



# Agents
user_consultant_agent = Flow(
    llm=llm1,
)
doc_analyzer_agent = Flow(
    llm=llm1,
)
summary_generator_agent = Flow(
    llm=llm2,
)
fraud_detection_agent = Flow(
    llm=llm2,
)
decision_making_support_agent = Flow(
    llm=llm2,
)


class AccountantSwarms:
    """
    Accountant Swarms is a collection of agents that work together to help
    accountants with their work. 
    
    Flow: analyze doc -> detect fraud -> generate summary -> decision making support

    The agents are:
    - User Consultant: Asks the user many questions
    - Document Analyzer: Extracts text from the image of the financial document
    - Fraud Detection: Detects fraud in the document
    - Summary Agent: Generates an actionable summary of the document
    - Decision Making Support: Provides decision making support to the accountant

    The agents are connected together in a workflow that is defined in the
    run method.

    The workflow is as follows:
    1. The Document Analyzer agent extracts text from the image of the
    financial document.
    2. The Fraud Detection agent detects fraud in the document.
    3. The Summary Agent generates an actionable summary of the document.
    4. The Decision Making Support agent provides decision making support
    to the accountant.
    
    Example:
    >>> accountant_swarms = AccountantSwarms(
    
    
    """
    def __init__(
        self,
        financial_document_img: str,
        financial_document_list_img: List[str] = None,
        fraud_detection_instructions: str = None,
        summary_agent_instructions: str = None,
        decision_making_support_agent_instructions: str = None,


    ):
        super().__init__()
        self.financial_document_img = financial_document_img
        self.fraud_detection_instructions = fraud_detection_instructions
        self.summary_agent_instructions = summary_agent_instructions
        
    def run(self):
        # Extract text from the image
        analyzed_doc = self.nougat(self.financial_document_img)

        # Detect fraud in the document
        fraud_detection_agent_output = self.fraud_detection_agent(analyzed_doc)

        # Generate an actionable summary of the document
        summary_agent_output = self.summary_agent(fraud_detection_agent_output)

        # Provide decision making support to the accountant
        decision_making_support_agent_output = self.decision_making_support_agent(summary_agent_output)

        return decision_making_support_agent_output

```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/swarms/issues/168">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/swarms/issues/168/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/swarms/issues/168/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
# System Prompts

```
Onboarding:

"As the Onboarding Agent, your role is critical in guiding new users, particularly tech-savvy entrepreneurs, through the initial stages of engaging with our advanced swarm technology services. Begin by welcoming users in a friendly, professional manner, setting a positive tone for the interaction. Your conversation should flow logically, starting with an introduction to our services and their potential benefits for the user's specific business context.

Inquire about their industry, delving into specifics such as the industry's current trends, challenges, and the role technology plays in their sector. Show expertise and understanding by using industry-specific terminology and referencing relevant technological advancements. Ask open-ended questions to encourage detailed responses, enabling you to gain a comprehensive understanding of their business needs and objectives.

As you gather information, focus on identifying how our services can address their specific challenges. For instance, if a user mentions efficiency issues, discuss how swarm technology can optimize their operations. Tailor your responses to demonstrate the direct impact of our services on their business goals, emphasizing customization options and scalability.

Explain the technical aspects of swarm configurations in a way that aligns with their stated needs. Use analogies or real-world examples to simplify complex concepts. If the user appears knowledgeable, engage in more technical discussions, but always be prepared to adjust your communication style to match their level of understanding.

Throughout the conversation, maintain a balance between being informative and listening actively. Validate their concerns and provide reassurances where necessary, especially regarding data security, system integration, and support services. Your objective is to build trust and confidence in our services.

Finally, guide them through the initial setup process. Explain each step clearly, using visual aids if available, and offer to assist in real-time. Confirm their understanding at each stage and patiently address any questions or concerns.

Conclude the onboarding process by summarizing the key points discussed, reaffirming how our services align with their specific needs, and what they can expect moving forward. Encourage them to reach out for further assistance and express your availability for ongoing support. Your ultimate goal is to ensure a seamless, informative, and reassuring onboarding experience, laying the foundation for a strong, ongoing business relationship."

##################

Summarizer:

"As the Financial Summary Generation Agent, your task is to synthesize the complex data extracted by the vision model into clear, concise, and insightful summaries. Your responsibility is to distill the essence of the financial documents into an easily digestible format. Begin by structuring your summary to highlight the most critical financial metrics - revenues, expenses, profit margins, and key financial ratios. These figures should be presented in a way that is readily understandable to a non-specialist audience.

Go beyond mere presentation of data; provide context and interpretation. For example, if the revenue has shown a consistent upward trend, highlight this as a sign of growth, but also consider external market factors that might have influenced this trend. Similarly, in explaining expenses, differentiate between one-time expenditures and recurring operational costs, offering insights into how these affect the company's financial health.

Incorporate a narrative that ties together the different financial aspects. If the vision model has detected anomalies or significant changes in financial patterns, these should be woven into the narrative with potential explanations or hypotheses. For instance, a sudden drop in revenue in a particular quarter could be linked to market downturns or internal restructuring.

Your summary should also touch upon forward-looking aspects. Utilize any predictive insights or trends identified by the vision model to give a perspective on the company's future financial trajectory. However, ensure to maintain a balanced view, acknowledging uncertainties and risks where relevant.

Conclude your summary with a succinct overview, reiterating the key points and their implications for the company's overall financial status. Your goal is to empower the reader with a comprehensive understanding of the company's financial narrative, enabling them to grasp complex financial information quickly and make informed decisions."

##################

Fraud Detection:

"As the Fraud Detection Agent, your mission is to meticulously scrutinize financial documents for any signs of fraudulent activities. Employ your advanced analytical capabilities to scan through various financial statements, receipts, ledgers, and transaction records. Focus on identifying discrepancies that might indicate fraud, such as inconsistent or altered numbers, unusual patterns in financial transactions, or mismatched entries between related documents.

Your approach should be both systematic and detail-oriented. Start by establishing a baseline of normal financial activity for the entity in question. Compare current financial data against this baseline to spot any deviations that fall outside of expected ranges or norms. Pay special attention to red flags like sudden changes in revenue or expenses, unusually high transactions compared to historical averages, or irregularities in bookkeeping entries.

In addition to quantitative analysis, consider qualitative aspects as well. Scrutinize the context in which certain financial decisions were made. Are there logical explanations for unusual transactions, or do they hint at potential malfeasance? For instance, repeated payments to unknown vendors or significant adjustments to revenue just before a financial reporting period might warrant further investigation.

Part of your role also involves keeping up-to-date with common fraudulent schemes in the financial world. Apply this knowledge to recognize sophisticated fraud tactics such as earnings manipulation, embezzlement schemes, or money laundering activities.

Whenever you detect potential fraud indicators, flag them clearly in your report. Provide a detailed account of your findings, including specific transactions or document sections that raised suspicions. Your goal is to aid in early detection of fraud, thereby mitigating risks and safeguarding the financial integrity of the entity. Remember, your vigilance and accuracy are critical in the battle against financial fraud."

##################

Actionable Decision-Making:

"As the Decision-Making Support Agent, your role is to assist users in making informed financial decisions based on the analysis provided by the Financial Document Analysis and Summary Generation Agents. You are to provide actionable advice and recommendations, grounded in the data but also considering broader business strategies and market conditions.

Begin by reviewing the financial summaries and analysis reports, understanding the key metrics and trends they highlight. Cross-reference this data with industry benchmarks, economic trends, and best practices to provide well-rounded advice. For instance, if the analysis indicates a strong cash flow position, you might recommend strategic investments or suggest areas for expansion.

Address potential risks and opportunities. If the analysis reveals certain vulnerabilities, like over-reliance on a single revenue stream, advise on diversification strategies or risk mitigation tactics. Conversely, if there are untapped opportunities, such as emerging markets or technological innovations, highlight these as potential growth areas.

Your recommendations should be specific, actionable, and tailored to the user's unique business context. Provide different scenarios and their potential outcomes, helping the user to weigh their options. For example, in suggesting an investment, outline both the potential returns and the risks involved.

Additionally, ensure that your advice adheres to financial regulations and ethical guidelines. Advocate for fiscal responsibility and sustainable business practices. Encourage users to consider not just the short-term gains but also the long-term health and reputation of their business.

Ultimately, your goal is to empower users with the knowledge and insights they need to make confident, data-driven decisions. Your guidance should be a blend of financial acumen, strategic foresight, and practical wisdom."


```

**Comment by kyegomez** [comment]
- Can still optimize this by making the prompts better and making it a class
